In [34]:
import numpy as np
from scipy import linalg as LA
np.set_printoptions(precision=2)
X = np.array([
        [0.387,4878, 5.42],
        [0.723,12104,5.25],
        [1,12756,5.52],
        [1.524,6787,3.94],
    ])

In [35]:
X = X - np.mean(X, axis=0)

# Eigenvalue Approach

In [47]:
cov = np.cov(X, rowvar = False)
evals , evecs = LA.eigh(cov)
idx = np.argsort(evals)[::-1]
P = evecs[:,idx]
evals = evals[idx]
score_eig = np.dot(X, evecs) 

In [48]:
P.T

array([[-1.22e-05, -1.00e+00, -7.30e-05],
       [-5.66e-01, -5.33e-05,  8.24e-01],
       [ 8.24e-01, -5.14e-05,  5.66e-01]])

In [49]:
score_eig

array([[ 8.38e-03,  8.41e-01,  4.25e+03],
       [-1.82e-01,  1.26e-01, -2.97e+03],
       [ 1.65e-01,  1.57e-01, -3.62e+03],
       [ 8.87e-03, -1.12e+00,  2.34e+03]])

# SVD

In [38]:
from numpy.linalg import svd 
U, S, PTrans = svd(X, full_matrices=False)
T=np.dot(U,Sigma)
print("U:")
print(U)
print("S used for building Sigma:")
print(S)
Sigma = np.diag(S)
print("Sigma:")
print(Sigma)
print("PTrans")
print(PTranspose)
print("Scores")
print(T)
print("CHECK FOR SVD:")
print("U * Sigma * PTrans")
print(np.dot(U, np.dot(Sigma, PTranspose)))
print("X")
print(X)

U:
[[-0.63  0.59 -0.03]
 [ 0.44  0.09  0.74]
 [ 0.54  0.11 -0.67]
 [-0.35 -0.79 -0.04]]
S used for building Sigma:
[6.75e+03 1.42e+00 2.46e-01]
Sigma:
[[6.75e+03 0.00e+00 0.00e+00]
 [0.00e+00 1.42e+00 0.00e+00]
 [0.00e+00 0.00e+00 2.46e-01]]
PTrans
[[ 1.22e-05  1.00e+00  7.30e-05]
 [-5.66e-01 -5.33e-05  8.24e-01]
 [-8.24e-01  5.14e-05 -5.66e-01]]
Scores
[[-4.25e+03  8.41e-01 -8.38e-03]
 [ 2.97e+03  1.26e-01  1.82e-01]
 [ 3.62e+03  1.57e-01 -1.65e-01]
 [-2.34e+03 -1.12e+00 -8.87e-03]]
CHECK FOR SVD:
U * Sigma * PTrans
[[-5.22e-01 -4.25e+03  3.88e-01]
 [-1.85e-01  2.97e+03  2.17e-01]
 [ 9.15e-02  3.62e+03  4.87e-01]
 [ 6.15e-01 -2.34e+03 -1.09e+00]]
X
[[-5.21e-01 -4.25e+03  3.88e-01]
 [-1.85e-01  2.97e+03  2.18e-01]
 [ 9.15e-02  3.62e+03  4.87e-01]
 [ 6.16e-01 -2.34e+03 -1.09e+00]]


In [45]:
S**2

array([4.56e+07, 2.01e+00, 6.07e-02])

In [46]:
evals

array([1.52e+07, 6.71e-01, 2.02e-02])